
import { JobListing, Article, UserProfile } from './types';

export const INITIAL_USER_PROFILE: UserProfile = {
  name: '田中 太郎',
  gender: 'male',
  phone: '090-1234-5678',
  university: '東京工科大学',
  faculty: '工学部',
  department: '情報工学科',
  graduationYear: '2026',
  email: 'tanaka@example.com',
  address: '東京都八王子市...',
  githubUrl: 'https://github.com/tanakataro',
  skills: 'React, TypeScript, Go',
};

export const JOB_LISTINGS: JobListing[] = [
  {
    id: '1',
    title: '文章で人を感動させるライター・コピーライターになろう！第二新卒歓迎',
    company: {
      id: 'c1',
      name: '株式会社NextGen Creative',
      logoUrl: 'https://picsum.photos/id/64/100/100',
      location: '東京都 港区',
      mission: 'クリエイティブの力で、企業のポテンシャルを解放する',
      description: '日本を代表する大手企業500社以上をクライアントに持ち、ブランディング・マーケティング・広報などの幅広い領域で、企業価値を高める支援を行っています。',
      url: 'https://example.com',
      address: '東京都港区浜松町2-4-1 世界貿易センタービル',
      established: '2020年4月',
      representative: '山田 太郎',
      industry: 'コンサルティング / クリエイティブ',
      coverImage: 'https://picsum.photos/id/1/800/450',
      employees: '120名'
    },
    coverImageUrl: 'https://picsum.photos/id/1/800/450',
    tags: ['ライター', '編集', 'マーケティング', '未経験歓迎'],
    salary: '時給 1,200円〜',
    type: 'Long-term',
    workStyle: 'Hybrid',
    description: `何故、NextGen Creativeに入社したのか？...`, // Truncated for brevity
    requiredSkills: ['ライティング', 'コミュニケーション能力'],
    businessContent: `【大手企業に特化した『コンサルティング×クリエイティブ』集団】...`, // Truncated
    jobDetail: `就活では、出版業界は狭き門。新卒では諦めたライターという道を...`, // Truncated
    skillsGained: ['プロフェッショナルなライティングスキル', '大手企業の経営課題への理解', '編集・ディレクション能力'],
    selectionFlow: [
      { step: 1, title: '書類選考', description: 'プロフィールをもとに選考します' },
      { step: 2, title: 'カジュアル面談', description: 'オフィスでざっくばらんにお話しましょう' },
      { step: 3, title: 'インターン開始', description: 'OJT形式でスタート' }
    ],
    // New Fields
    alumniDestinations: '電通, 博報堂, リクルート, サイバーエージェント, キーエンス',
    salaryDetail: '時給1,200円〜（昇給あり）\n※スキル・経験に応じて決定します',
    probationPeriod: '3ヶ月',
    probationSalary: '時給1,150円',
    transportationAllowance: '全額支給',
    requirements: '・文章を書くことが好きな方\n・週3日以上勤務できる方\n・基本的なPC操作ができる方',
    workDays: '月, 火, 水, 木, 金',
    workFrequency: '週3日〜',
    workHours: '10:00 〜 19:00 (1日5時間〜)',
    otherConditions: '・PC貸与あり\n・服装自由\n・フリードリンクあり',
    targetGrade: '全学年対象',
    numberOfHires: '3名',
    workLocation: '東京都港区浜松町2-4-1',
    nearestStation: '浜松町駅 徒歩3分, 大門駅 徒歩5分'
  },
  {
    id: '2',
    title: 'Go言語を用いた高負荷分散システムのバックエンド開発インターン',
    company: {
      id: 'c2',
      name: 'CyberScale Inc.',
      logoUrl: 'https://picsum.photos/id/60/100/100',
      location: '東京都 港区',
      mission: '世界を繋ぐインフラを創る',
      description: '秒間数百万リクエストを処理するアドテクプラットフォームを運営...',
      address: '東京都港区六本木6-10-1',
      established: '2018年9月',
      industry: 'アドテクノロジー',
      coverImage: 'https://picsum.photos/id/20/800/450',
      employees: '80名'
    },
    coverImageUrl: 'https://picsum.photos/id/20/800/450',
    tags: ['Go', 'gRPC', 'Kubernetes', 'Microservices'],
    salary: '時給 1,800円〜',
    type: 'Long-term',
    workStyle: 'Hybrid',
    description: '月間1億リクエストを捌く大規模広告配信システムのバックエンド刷新プロジェクト...',
    requiredSkills: ['Go', 'Docker'],
    businessContent: 'デジタル広告配信プラットフォーム（DSP/SSP）の開発・運営。',
    jobDetail: '・Go言語を用いたAPIサーバーの設計・開発\n・gRPCによるマイクロサービス間通信の実装...',
    skillsGained: ['高負荷対策のノウハウ', 'マイクロサービスアーキテクチャの設計思想', 'Go言語の深い知識'],
    selectionFlow: [
        { step: 1, title: 'コーディングテスト', description: 'オンラインでアルゴリズムの問題を解いていただきます' },
        { step: 2, title: 'カジュアル面談', description: 'エンジニアとの技術対話' },
        { step: 3, title: '採用', description: '' }
      ],
    // New Fields
    alumniDestinations: 'Google, AWS, メルカリ, LINE, DeNA',
    salaryDetail: '時給1,800円〜2,500円',
    probationPeriod: '1ヶ月',
    probationSalary: '時給1,800円',
    transportationAllowance: '上限3万円/月',
    requirements: '・Webアプリケーションの開発経験がある方\n・Gitを用いたチーム開発経験',
    workDays: '平日',
    workFrequency: '週3日〜',
    workHours: 'フレックス（コアタイムなし）',
    otherConditions: '・最新のMacBook Pro支給\n・技術書購入補助\n・カンファレンス参加費補助',
    targetGrade: '学部3年以上推奨',
    numberOfHires: '若干名',
    workLocation: '東京都港区六本木6-10-1 六本木ヒルズ',
    nearestStation: '六本木駅 直結'
  },
  // Dummy duplicate job for CyberScale Inc. (c2)
  {
    id: '2b',
    title: '【インフラ/SRE】大規模トラフィックを支えるクラウド基盤構築',
    company: {
      id: 'c2', // Same ID as above
      name: 'CyberScale Inc.',
      logoUrl: 'https://picsum.photos/id/60/100/100',
      location: '東京都 港区',
      mission: '世界を繋ぐインフラを創る',
      description: '秒間数百万リクエストを処理するアドテクプラットフォームを運営...',
      address: '東京都港区六本木6-10-1',
      established: '2018年9月',
      industry: 'アドテクノロジー',
      coverImage: 'https://picsum.photos/id/20/800/450',
      employees: '80名'
    },
    coverImageUrl: 'https://picsum.photos/id/3/800/450',
    tags: ['AWS', 'Terraform', 'Linux', 'SRE'],
    salary: '時給 1,800円〜',
    type: 'Long-term',
    workStyle: 'Remote',
    description: 'サービスの急成長に伴い、インフラ基盤の強化・自動化を推進するSREチームのアシスタントを募集します。',
    requiredSkills: ['Linux', 'AWS'],
    businessContent: 'デジタル広告配信プラットフォームのインフラ運用・構築',
    jobDetail: '・Terraformを用いたIaC推進\n・Datadog等を用いた監視基盤の構築...',
    skillsGained: ['大規模インフラの運用経験', 'IaCの実践スキル', 'トラブルシューティング能力'],
    selectionFlow: [
        { step: 1, title: '書類選考', description: '' },
        { step: 2, title: '技術面談', description: '' }
    ],
    alumniDestinations: 'AWS, Google, CyberAgent',
    salaryDetail: '時給1,800円〜',
    probationPeriod: '1ヶ月',
    probationSalary: '同額',
    transportationAllowance: '全額支給',
    requirements: '・Linuxの基本的なコマンド操作ができる方\n・クラウド(AWS/GCP)への興味関心',
    workDays: '平日',
    workFrequency: '週3日〜',
    workHours: '10:00 - 19:00',
    otherConditions: '・リモートワーク中心\n・PC支給あり',
    targetGrade: '不問',
    numberOfHires: '1名',
    workLocation: '東京都港区六本木',
    nearestStation: '六本木駅'
  },
  {
    id: '3',
    title: 'React/Next.jsを用いたモダンなSaaSプロダクトのフロントエンド開発',
    company: {
      id: 'c3',
      name: 'DesignShift',
      logoUrl: 'https://picsum.photos/id/96/100/100',
      location: '大阪府 大阪市',
      mission: 'デザインの力でビジネスを変える',
      description: 'UI/UXに徹底的にこだわったBtoB SaaSを提供。グッドデザイン賞受賞歴あり。',
      address: '大阪府大阪市北区大深町',
      established: '2021年2月',
      industry: 'SaaS / HR Tech',
      coverImage: 'https://picsum.photos/id/48/800/450',
      employees: '30名'
    },
    coverImageUrl: 'https://picsum.photos/id/48/800/450',
    tags: ['TypeScript', 'React', 'Next.js', 'Tailwind'],
    salary: '時給 1,400円〜',
    type: 'Long-term',
    workStyle: 'Remote',
    description: 'UI/UXに拘った人事労務SaaSの開発...',
    requiredSkills: ['React', 'TypeScript'],
    businessContent: '人事労務管理SaaS「ShiftHR」の企画・開発。',
    jobDetail: '・Next.js (App Router) を用いたフロントエンド実装...',
    skillsGained: ['モダンフロントエンドのエコシステム', 'ピクセルパーフェクトな実装力', 'アクセシビリティ（WCAG）の知識'],
    selectionFlow: [
        { step: 1, title: 'ポートフォリオ審査', description: '' },
        { step: 2, title: 'カジュアル面談', description: '' }
    ],
    alumniDestinations: 'SmartHR, ユーザベース, クックパッド',
    salaryDetail: '時給1,400円〜',
    probationPeriod: 'なし',
    probationSalary: '同額',
    transportationAllowance: 'リモートのためなし',
    requirements: '・ReactまたはVueの実装経験',
    workDays: '自由',
    workFrequency: '週15時間〜',
    workHours: '自由',
    otherConditions: '・フルリモート推奨\n・Slackでの非同期コミュニケーション',
    targetGrade: '不問',
    numberOfHires: '2名',
    workLocation: 'フルリモート（出社可：大阪オフィス）',
    nearestStation: '大阪駅 徒歩5分'
  },
  {
    id: '4',
    title: '未経験可！Rustを使ったブロックチェーンコア開発のアシスタント',
    company: {
      id: 'c4',
      name: 'ChainWorks',
      logoUrl: 'https://picsum.photos/id/180/100/100',
      location: '福岡県 福岡市',
      industry: 'Web3 / Blockchain',
      coverImage: 'https://picsum.photos/id/60/800/450',
      employees: '15名'
    },
    coverImageUrl: 'https://picsum.photos/id/60/800/450',
    tags: ['Rust', 'Blockchain', 'Web3'],
    salary: '時給 1,200円〜',
    type: 'Short-term',
    workStyle: 'On-site',
    description: '次世代L1ブロックチェーンのコアロジック実装サポート...',
    requiredSkills: ['C++', 'Rust'],
    businessContent: 'パブリックブロックチェーンの研究開発。',
    jobDetail: '・Rustによるスマートコントラクト実行基盤の実装補助...',
    skillsGained: ['Rust言語', '分散システムの理論', '暗号技術の基礎'],
    selectionFlow: [
        { step: 1, title: '書類選考', description: '' },
        { step: 2, title: 'カジュアル面談', description: '' }
    ],
    alumniDestinations: 'Ethereum Foundation, Startups',
    salaryDetail: '時給1,200円',
    probationPeriod: 'なし',
    probationSalary: '-',
    transportationAllowance: '支給',
    requirements: '・CS専攻の学生優遇',
    workDays: '平日',
    workFrequency: '週2日〜',
    workHours: '10:00 - 18:00',
    otherConditions: '・髪型服装自由',
    targetGrade: '大学院生歓迎',
    numberOfHires: '1名',
    workLocation: '福岡県福岡市博多区',
    nearestStation: '博多駅'
  },
  {
    id: '5',
    title: 'Flutterでのヘルスケアアプリ新規立ち上げメンバー募集',
    company: {
      id: 'c5',
      name: 'HealthTech Lab',
      logoUrl: 'https://picsum.photos/id/119/100/100',
      location: '東京都 新宿区',
      industry: 'HealthTech',
      coverImage: 'https://picsum.photos/id/96/800/450',
      employees: '50名'
    },
    coverImageUrl: 'https://picsum.photos/id/96/800/450',
    tags: ['Flutter', 'Dart', 'Firebase', 'Mobile'],
    salary: '時給 1,600円〜',
    type: 'Long-term',
    workStyle: 'Remote',
    description: '人々の健康を支える新規アプリの立ち上げ...',
    requiredSkills: ['Flutter', 'Mobile Dev'],
    businessContent: '予防医療領域のモバイルアプリ開発。',
    jobDetail: '・Flutterを用いたiOS/Androidアプリのクロスプラットフォーム開発...',
    skillsGained: ['モバイルアプリのリリース経験', 'UI設計スキル', 'Firebase活用術'],
    selectionFlow: [
        { step: 1, title: 'カジュアル面談', description: '' },
        { step: 2, title: 'ハッカソン選考', description: '1day' }
    ],
    alumniDestinations: 'DeNA, CyberAgent',
    salaryDetail: '時給1,600円〜',
    probationPeriod: '1ヶ月',
    probationSalary: '1,500円',
    transportationAllowance: '全額',
    requirements: '・個人開発でアプリをリリースした経験',
    workDays: '週3日〜',
    workFrequency: '週20時間',
    workHours: 'フレックス',
    otherConditions: '・MacBook貸与',
    targetGrade: '不問',
    numberOfHires: '2名',
    workLocation: '東京都新宿区',
    nearestStation: '新宿駅'
  },
  {
    id: '6',
    title: '【急募】Unityエンジニア！メタバース空間の演出・ギミック実装',
    company: {
      id: 'c6',
      name: 'VirtualX',
      logoUrl: 'https://picsum.photos/id/160/100/100',
      location: '東京都 渋谷区',
      industry: 'Metaverse / VR',
      coverImage: 'https://picsum.photos/id/180/800/450',
      employees: '20名'
    },
    coverImageUrl: 'https://picsum.photos/id/180/800/450',
    tags: ['Unity', 'C#', 'VR/AR', '3D'],
    salary: '時給 1,500円〜',
    type: 'Short-term',
    workStyle: 'Hybrid',
    description: '大規模メタバースイベントの空間設計とインタラクション実装...',
    requiredSkills: ['Unity', 'C#'],
    businessContent: 'VRイベントプラットフォームの企画・運営。',
    jobDetail: '・Unityを用いた3D空間の構築...',
    skillsGained: ['3D数学', 'オンラインゲームの同期技術', 'C#上級スキル'],
    selectionFlow: [
        { step: 1, title: 'ポートフォリオ選考', description: '作品提出必須' },
        { step: 2, title: 'カジュアル面談', description: '' }
    ],
    alumniDestinations: 'ゲーム会社多数',
    salaryDetail: '時給1,500円〜',
    probationPeriod: 'なし',
    probationSalary: '-',
    transportationAllowance: '全額',
    requirements: '・Unityでのゲーム制作経験',
    workDays: '平日のみ',
    workFrequency: '週3日〜',
    workHours: '11:00 - 20:00',
    otherConditions: '・VRヘッドセット貸出可',
    targetGrade: '全学年',
    numberOfHires: '5名',
    workLocation: '東京都渋谷区',
    nearestStation: '渋谷駅'
  },
];

export const ARTICLES: Article[] = [
  {
    id: 1,
    title: '未経験からAIエンジニアへ。長期インターンで学ぶべきこととは？',
    date: '2025.04.12',
    category: 'CAREER',
    image: 'https://picsum.photos/id/101/600/400',
    content: `...` 
  },
  {
    id: 2,
    title: '【25卒・26卒】メガベンチャー内定者が語る、Githubプロフィールの作り方',
    date: '2025.04.10',
    category: 'SKILL',
    image: 'https://picsum.photos/id/180/600/400',
    content: `...` 
  },
  {
    id: 3,
    title: 'リモートインターンのリアル。コミュニケーションの課題と解決策',
    date: '2025.04.05',
    category: 'WORK STYLE',
    image: 'https://picsum.photos/id/1/600/400',
    content: `...` 
  },
  {
    id: 4,
    title: 'Go言語の需要が急上昇中？バックエンドエンジニアのキャリア戦略',
    date: '2025.04.01',
    category: 'TREND',
    image: 'https://picsum.photos/id/20/600/400',
    content: `...` 
  },
];
